//! Installs the four Jupyter kernelspecs (csv/tsv/ssv/psv) that point back
//! at this binary.
//!
//! A Jupyter data directory belongs to the user, not to this extension, so
//! nothing here ever runs on its own: the only callers are the explicit
//! `csv-ls install-kernelspecs` / `uninstall-kernelspecs` subcommands and an
//! LSP start that the user opted in to (see `main::install_kernelspecs_if_opted_in`).

use std::path::PathBuf;

use serde_json::{json, Value};

type Error = Box<dyn std::error::Error + Sync + Send>;

struct Spec {
    name: &'static str,
    display: &'static str,
    delimiter: &'static str,
}

const SPECS: [Spec; 4] = [
    Spec {
        name: "csv",
        display: "CSV Table",
        delimiter: ",",
    },
    Spec {
        name: "tsv",
        display: "TSV Table",
        delimiter: "\t",
    },
    Spec {
        name: "ssv",
        display: "SSV Table",
        delimiter: ";",
    },
    Spec {
        name: "psv",
        display: "PSV Table",
        delimiter: "|",
    },
];

/// $JUPYTER_DATA_DIR if set; else the platform's standard Jupyter data dir.
fn data_dir() -> PathBuf {
    if let Some(v) = std::env::var_os("JUPYTER_DATA_DIR") {
        if !v.is_empty() {
            return PathBuf::from(v);
        }
    }
    if cfg!(target_os = "macos") {
        if let Some(home) = std::env::var_os("HOME") {
            return PathBuf::from(home).join("Library/Jupyter");
        }
    }
    if cfg!(target_os = "windows") {
        if let Some(appdata) = std::env::var_os("APPDATA") {
            return PathBuf::from(appdata).join("jupyter");
        }
    }
    let base = std::env::var_os("XDG_DATA_HOME")
        .filter(|v| !v.is_empty())
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            let home = std::env::var_os("HOME").unwrap_or_default();
            PathBuf::from(home).join(".local/share")
        });
    base.join("jupyter")
}

fn kernel_json(spec: &Spec, exe: &std::path::Path) -> Value {
    json!({
        "argv": [exe.to_string_lossy(), "kernel", "-f", "{connection_file}"],
        "display_name": spec.display,
        "language": spec.name,
        "interrupt_mode": "message",
        "env": {
            "CSV_KERNEL_DELIMITER": spec.delimiter,
            "CSV_KERNEL_LANGUAGE": spec.name,
        },
        "metadata": {"generated_by": "csv-ls"},
    })
}

/// A kernelspec we own and may overwrite: one carrying our marker, or a
/// legacy spec from the retired Python kernel (scripts/install-kernel.sh
/// wrote argv pointing at csv_kernel.py, with no marker) — those must be
/// migrated, not protected, or they keep pointing at a deleted file.
fn was_generated_by_us(existing: &Value) -> bool {
    let marker = existing
        .get("metadata")
        .and_then(|m| m.get("generated_by"))
        .and_then(Value::as_str)
        == Some("csv-ls");
    let legacy_python = existing
        .get("argv")
        .and_then(Value::as_array)
        .is_some_and(|argv| {
            argv.iter()
                .any(|a| a.as_str().is_some_and(|s| s.contains("csv_kernel.py")))
        });
    marker || legacy_python
}

/// Write kernels/{csv,tsv,ssv,psv}/kernel.json under the resolved data dir.
/// A kernelspec is (re)written if it doesn't exist yet, or if it was
/// generated by us and its content is stale (e.g. the binary moved); a
/// kernelspec that isn't ours (missing/different `metadata.generated_by`) is
/// never touched. `explicit` controls whether progress/skip notes are
/// printed (only the `install-kernelspecs` subcommand wants that).
pub fn install(explicit: bool) -> Result<(), Error> {
    let exe = std::env::current_exe()?;
    let kernels_dir = data_dir().join("kernels");
    for spec in &SPECS {
        let dir = kernels_dir.join(spec.name);
        let path = dir.join("kernel.json");
        let new_value = kernel_json(spec, &exe);

        let action = match std::fs::read_to_string(&path) {
            Err(_) => Some("installed"),
            Ok(existing_text) => match serde_json::from_str::<Value>(&existing_text) {
                Ok(existing) if was_generated_by_us(&existing) => {
                    if existing == new_value {
                        None
                    } else {
                        Some("updated")
                    }
                }
                _ => {
                    if explicit {
                        println!("skipped {}: not managed by csv-ls", path.display());
                    }
                    None
                }
            },
        };

        if let Some(verb) = action {
            // Created here, not up front, so a run that writes nothing (every
            // spec current, or every spec foreign) leaves no empty directories.
            std::fs::create_dir_all(&dir)?;
            let mut text = serde_json::to_string_pretty(&new_value)?;
            text.push('\n');
            std::fs::write(&path, text)?;
            if explicit {
                println!("{verb} {}", path.display());
            }
        }
    }
    Ok(())
}

/// Remove the kernelspecs csv-ls installed, so uninstalling the extension
/// doesn't leave four kernels pointing at a deleted binary in every Jupyter
/// frontend's kernel list. Ownership is judged exactly as on install: a spec
/// that isn't ours is reported and left alone.
pub fn uninstall() -> Result<(), Error> {
    let kernels_dir = data_dir().join("kernels");
    for spec in &SPECS {
        let dir = kernels_dir.join(spec.name);
        let path = dir.join("kernel.json");
        let Ok(existing_text) = std::fs::read_to_string(&path) else {
            continue;
        };
        match serde_json::from_str::<Value>(&existing_text) {
            Ok(existing) if was_generated_by_us(&existing) => {
                std::fs::remove_file(&path)?;
                // remove_dir, not remove_dir_all: anything else the user put
                // in the kernel directory (logo PNGs, say) keeps the
                // directory alive rather than being deleted along with it.
                let _ = std::fs::remove_dir(&dir);
                println!("removed {}", path.display());
            }
            _ => println!("skipped {}: not managed by csv-ls", path.display()),
        }
    }
    Ok(())
}
